export const CREDENTIALS_USER_ID_CHANGED = 'CREDENTIALS_USER_ID_CHANGED'
export const CREDENTIALS_EMAIL_CHANGED = 'CREDENTIALS_EMAIL_CHANGED'
export const FETCH_USER_PENDING = 'FETCH_USER_PENDING'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'
export const CREDENTIALS_INVALID_EMAIL = 'CREDENTIALS_INVALID_EMAIL'
export const CREDENTIALS_INVALID_USER_ID = 'CREDENTIALS_INVALID_USER_ID'
export const CREDENTIALS_FETCH_INITIAL_STATE = 'CREDENTIALS_FETCH_INITIAL_STATE'
export const CREDENTIALS_FETCHED_INITIAL_STATE =
  'CREDENTIALS_FETCHED_INITIAL_STATE'

export const USER_AUTH_PENDING = 'USER_AUTH_PENDING'
export const USER_AUTH_ENTER_SUCCESS = 'USER_AUTH_ENTER_SUCCESS'
export const USER_AUTH_ENTER_FAIL = 'USER_AUTH_ENTER_FAIL'
export const USER_AUTH_LEAVE_SUCCESS = 'USER_AUTH_LEAVE_SUCCESS'
export const USER_AUTH_LEAVE_FAIL = 'USER_AUTH_LEAVE_FAIL'
export const USER_AUTH_CHANGE_SELECTED_LAB = 'USER_AUTH_CHANGE_SELECTED_LAB'

export const USER_STATE = 'issuesAuthUserState'
